# Combining DataFrames With Pandas - Lab

## Introduction

In this lab, we'll gain practice combining DataFrames through concatenation.  We'll also learn to read in tables from a database and store them in separate tables, as well as how to execute various types of joins to selectively combine the information stored in the tables!


## Objectives:
You will be able to:
* Understand and explain when to use DataFrame joins and merges
* Be able to use pd.merge when combining DataFrames based on column values
* Understand, explain and use a range of DataFrame merge types: outer, inner, left and right
* Use pd.concat() to stack DataFrames

## Getting Started

We'll start with a quick section to help us gain practice with concatenating datasets using `pd.concat()`.

### Concatenating DataFrames

Run the cell below to create some sample DataFrames for us to work with.

In [3]:
import pandas as pd
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                    index=[0, 1, 2, 3])


df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                    index=[4, 5, 6, 7])

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'], 
                    'D': ['D8', 'D9', 'D10', 'D11']},
                    index=[8, 9, 10, 11])

Now that we have multiple DataFrames to work with, we can execute a concatenation to join them together.  

In the cell below, concatenate the 3 DataFrames together using the appropriate function.

In [4]:
to_concat = [df1, df2, df3]
combined_df = pd.concat(to_concat)
combined_df

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

**_EXPECTED OUTPUT:_**

<img src="er1.png">

### Setting Join Conditions With Concatenation

We can also specify if the concatenation is an **_Outer Join_** or an **_Inner Join_**.  Next, we'll execute an inner join. Before we do, we need to create another table that contains some overlapping index values with a DataFrame that already exists.  

Run the cell below to create the new DataFrame.

In [5]:
df4 = pd.DataFrame({'B': ['B2', 'B3', 'B6', 'B7'],
                    'D': ['D2', 'D3', 'D6', 'D7'],
                    'F': ['F2', 'F3', 'F6', 'F7']},
                    index=[2, 3, 6, 7])

Now, in the cell below, use the `pd.concat()` method to join DataFrames 1 and 4.  However, this time, specify that the `join` is `'inner'`, and `axis=1`.

In [6]:
df1_and_4 = pd.concat([df1, df4], axis=1, join='inner')
df1_and_4

    A   B   C   D   B   D   F
2  A2  B2  C2  D2  B2  D2  F2
3  A3  B3  C3  D3  B3  D3  F3

**_EXPECTED OUTPUT:_**

<img src='er2.png'>

We'll notice that in this case, the results returned contain only the rows with indexes that exist in both tables--rows 2 and 3.  The resulting table contains the values for each column in both tables for the rows.  

Note that there are many, many ways that we can make full use of the `concat()` functionality in pandas to join DataFrames together--these are just a few of the most common examples pulled from the pandas documentation on the subject.  For a full view of all the ways we can use `pd.concat()`, see the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/merging.html)!

## Loading In Data From SQL Database Tables

Now, we'll move on to working with the Hearthstone cards database.  This database contains information on cards from the popular game, [Hearthstone](https://playhearthstone.com/en-us/)! For full information on the dataset, see the  [kaggle page](https://www.kaggle.com/jeradrose/hearthstone-cards) for this dataset. 

This database consists of the following tables:

* _cards_
* *dust_costs*
* _entourages_
* _mechanics_
* *play_requirements*

Many of rows in each table--but not all--correspond to the same cards. As such, each table contains a column called `card_id` which acts as a **_Primary Key_** for each table.  We'll make use of these keys to **_join_** the different tables together into a single DataFrame.  We'll also experiment with different types of joins to help us decide exactly what information we want to combine.  

Before we can begin working with the database, we'll first need to connect to it.  For this, we'll use the `sqlalchemy` library.

In the cell below:

* Import the `create_engine` module from `sqlalchemy`
* Create an engine that connects to `sqlite:///database.sqlite`.

In [7]:
from sqlalchemy import create_engine
engine = create_engine('sqlite:///database.sqlite')

Now that we've successfully connected to our Database, we'll make use of pandas to read in each table individually.  

In the cell below, read in each sql table into separate pandas DataFrames using the `read_sql_table` method.  

The first argument should be a string corresponding to the name of the table, and the second argument should be the `engine` object we created in the cell above. 

If you're unsure of how to do this, see the [documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_sql_table.html).

In [8]:
cards_df = pd.read_sql_table('cards', engine)
dust_df = pd.read_sql_table('dust_costs', engine)
entourages_df = pd.read_sql_table('entourages', engine)
mechanics_df = pd.read_sql_table('mechanics', engine)
play_requirements_df = pd.read_sql_table('play_requirements', engine)

Great.  Now, let's set the correct column, `card_id`, as the index column for each of these tables, and then display each to ensure that everything is as expected.  

For each of the dataframes we created in the cell above, call the `.set_index()` method and pass in `card_id`.  Also set `inplace=True`.  Then, display the head of each respective DataFrame to ensure everything worked.  

**_NOTE:_** Since we are performing this operation in place, running any cell a second time will result in pandas throwing an error.  If you need to run something a second time, restart the kernel using the jupyter notebook menu at the top of the page.

In [8]:
cards_df.set_index('card_id', inplace=True)
cards_df.head()

,player_class,type,name,set,text,cost,attack,health,rarity,collectible,flavor,race,how_to_earn,how_to_earn_golden,targeting_arrow_text,faction,durability
card_id,,,,,,,,,,,,,,,,,
KARA_00_07,MAGE,SPELL,Astral Portal,KARA,Summon a random <b>Legendary</b> minion.,1.0,NaN,NaN,None,NaN,None,None,None,None,None,None,NaN
NEW1_008a,DRUID,SPELL,Ancient Teachings,EXPERT1,Draw a card.,0.0,NaN,NaN,None,NaN,None,None,None,None,None,None,NaN
BRM_010t2,DRUID,MINION,Druid of the Flame,BRM,None,3.0,2.0,5.0,COMMON,NaN,None,BEAST,None,None,None,None,NaN
AT_132,NEUTRAL,MINION,Justicar Trueheart,TGT,<b>Battlecry:</b> Replace your starting Hero P...,6.0,6.0,3.0,LEGENDARY,1.0,It's like putting racing stripes and a giant s...,None,None,None,None,None,NaN
OG_141,NEUTRAL,MINION,Faceless Behemoth,OG,None,10.0,10.0,10.0,COMMON,1.0,"Rejected names: Forty-Foot Faceless, Big ol' N...",None,None,None,None,None,NaN

In [12]:
dust_df.set_index('card_id', inplace=True)
dust_df.head()

                      action  cost
card_id
BRM_010t2    CRAFTING_NORMAL    40
BRM_010t2    CRAFTING_GOLDEN   400
BRM_010t2  DISENCHANT_NORMAL     5
BRM_010t2  DISENCHANT_GOLDEN    50
AT_132       CRAFTING_NORMAL  1600

In [11]:
entourages_df.set_index('card_id', inplace=True)
entourages_df.head()

           entourage_card_id
card_id
KAR_A10_22        KAR_A10_09
KAR_A10_22        KAR_A10_02
KAR_A10_22        KAR_A10_08
KAR_A10_22        KAR_A10_04
KAR_A10_22        KAR_A10_05

In [13]:
mechanics_df.set_index('card_id', inplace=True)
mechanics_df.head()

                     mechanic
card_id
AT_132              BATTLECRY
GVG_011a  TAG_ONE_TURN_EFFECT
EX1_583             BATTLECRY
LOE_007t            EVIL_GLOW
LOE_007t   ImmuneToSpellpower

In [14]:
play_requirements_df.set_index('card_id', inplace=True)
play_requirements_df.head()

                     play_requirement  value
card_id
KARA_00_07       REQ_NUM_MINION_SLOTS      1
PRO_001a         REQ_NUM_MINION_SLOTS      1
NAX1_01          REQ_NUM_MINION_SLOTS      1
DS1h_292_H1           REQ_STEADY_SHOT      0
DS1h_292_H1  REQ_MINION_OR_ENEMY_HERO      0

### Executing Joins

Now that we have the tables loaded correctly, we're going to execute some joins. There are 4 different kinds of joins, which can best be visualized with venn diagrams:

<img src='joins.png'>

In these diagrams, each circle represents a DataFrame or SQL Table.  The left table is the table we are working with, and the right table is the table we want to join to the table we are working with.  We'll start by executing the most common type of join, an **_Inner Join_**.

In the cell below, join `cards_df` with `mechanics_df` using the built-in `.join()` method on the `cards_df` object. 

Pass in the following parameters:
* the table we want to join with, `mechanics_df`
* The `how` parameter set to the type of join we want, `'inner'`

In [12]:
cards_with_mechanics_df = cards_df.join(mechanics_df, how='inner')
cards_with_mechanics_df

ValueError: columns overlap but no suffix specified: Index(['card_id'], dtype='object')

Examine the output from the cell above and compare it to the original output of both the `cards_df` and `mechanics_df` DataFrame heads we displayed earlier.  Notice how it this now combines the columns from both?

**_Question_**

If you inspect the original `cards_df` DataFrame, you'll notice that it contains  2,819 records.  The result of our inner join, `cards_with_mechanics_df`, conntains only 1079 rows.  Why?

Write your answer below this line:
________________________________________________________________________________


### Other Types of Joins

By default, the `.join()` method performs a left join if no parameter is passed in for `how=`.  In the cell below, perform a **_Left Join_** of `cards_with_mechanics_df` and `play_requirements_df`, with `cards_with_mechanics_df` as the left table.  

Then, display `left_join_df` to inspect our results.

In [11]:
left_join_df = cards_with_mechanics.join(play_requirements)
left_join_df

NameError: name 'cards_with_mechanics' is not defined

Note that the results of this sort of join are dependent upon the position of each table--if we were to make `cards_with_mechanics_df` the right table and `play_requirements_df` the left table and then perform a **_Right Join_**, our results would be the same. 

**_Question:_**

Describe what was included from each table in this join.

Write your answer below this line:
________________________________________________________________________________



#### Outer Joins

In the cell below, perform an outer join between `cards_df` and `dust_df`. Since these tables contain columns with the same name, we'll need to specify a suffix for at least one of them, so that the column can be renamed to avoid a naming collision. 

During this join, set the `rsuffix` parameter to `_dust`

In [14]:
outer_join_df = cards_df.join(dust_df, rsuffix='_dust', how='outer')
outer_join_df

,card_id,player_class,type,name,set,text,cost,attack,health,rarity,collectible,flavor,race,how_to_earn,how_to_earn_golden,targeting_arrow_text,faction,durability,action,cost_dust
0,KARA_00_07,MAGE,SPELL,Astral Portal,KARA,Summon a random <b>Legendary</b> minion.,1.0,NaN,NaN,None,NaN,None,None,None,None,None,None,NaN,NaN,NaN
1,NEW1_008a,DRUID,SPELL,Ancient Teachings,EXPERT1,Draw a card.,0.0,NaN,NaN,None,NaN,None,None,None,None,None,None,NaN,NaN,NaN
2,BRM_010t2,DRUID,MINION,Druid of the Flame,BRM,None,3.0,2.0,5.0,COMMON,NaN,None,BEAST,None,None,None,None,NaN,NaN,NaN
3,AT_132,NEUTRAL,MINION,Justicar Trueheart,TGT,<b>Battlecry:</b> Replace your starting Hero P...,6.0,6.0,3.0,LEGENDARY,1.0,It's like putting racing stripes and a giant s...,None,None,None,None,None,NaN,NaN,NaN
4,OG_141,NEUTRAL,MINION,Faceless Behemoth,OG,None,10.0,10.0,10.0,COMMON,1.0,"Rejected names: Forty-Foot Faceless, Big ol' N...",None,None,None,None,None,NaN,NaN,NaN
5,CRED_17,NEUTRAL,MINION,Rob Pardo,CREDITS,You can't start a game without this minion in ...,9.0,9.0,9.0,LEGENDARY,NaN,None,None,None,None,None,None,NaN,NaN,NaN
6,OG_337e,NEUTRAL,ENCHANTMENT,Eve of Destruction,OG,Stats increased.,NaN,NaN,NaN,None,NaN,None,None,None,None,None,None,NaN,NaN,NaN
7,BRMA08_1H,NEUTRAL,HERO,General Drakkisath,BRM,None,NaN,NaN,50.0,None,NaN,None,None,None,None,None,None,NaN,NaN,NaN
8,GVG_011a,NEUTRAL,ENCHANTMENT,Shrink Ray,GVG,-2 Attack this turn.,NaN,NaN,NaN,None,NaN,None,None,None,None,None,None,NaN,NaN,NaN
9,NAX8_02H_TB,NEUTRAL,HERO_POWER,Harvest,TB,<b>Hero Power</b>\nDraw a card. Gain a Mana Cr...,2.0,NaN,NaN,None,NaN,None,None,None,None,None,None,NaN,NaN,NaN
10,AT_131,NEUTRAL,MINION,Eydis Darkbane,TGT,Whenever <b>you</b> target this minion with a ...,3.0,3.0,4.0,LEGENDARY,1.0,"HATES being called ""the wonder twins"".",None,None,None,None,None,NaN,NaN,NaN
11,CS2_122e,NEUTRAL,ENCHANTMENT,Enhanced,CORE,Raid Leader is granting this minion +1 Attack.,NaN,NaN,NaN,None,NaN,None,None,None,None,None,None,NaN,NaN,NaN
12,LOEA05_02ha,NEUTRAL,HERO_POWER,Trogg Hate Minions!,LOE,<b>Passive Hero Power</b>\n Enemy minions cost...,0.0,NaN,NaN,None,NaN,None,None,None,None,None,None,NaN,NaN,NaN
13,CS2_102_H1_AT_132,WARRIOR,HERO_POWER,Tank Up!,HERO_SKINS,<b>Hero Power</b>\nGain 4 Armor.,2.0,NaN,NaN,None,NaN,None,None,None,None,None,None,NaN,NaN,NaN
14,CFM_334e,NEUTRAL,ENCHANTMENT,Smuggling,GANGS,+2/+2 from Smuggler's Crate.,NaN,NaN,NaN,None,NaN,None,None,None,None,None,None,NaN,NaN,NaN
15,EX1_583,NEUTRAL,MINION,Priestess of Elune,EXPERT1,<b>Battlecry:</b> Restore 4 Health to your hero.,6.0,5.0,4.0,COMMON,1.0,"If she threatens to ""moon"" you, it's not what ...",None,None,None,None,None,NaN,NaN,NaN
16,TB_PickYourFate_11rand,NEUTRAL,SPELL,Dire Fate: Murlocs,TB,Turn each minion in play into a 1/1 Murloc.,0.0,NaN,NaN,None,NaN,None,None,None,None,None,None,NaN,NaN,NaN
17,LOE_007t,WARLOCK,SPELL,Cursed!,LOE,"While this is in your hand, take 2 damage at t...",2.0,NaN,NaN,None,NaN,None,None,None,None,None,None,NaN,NaN,NaN
18,CFM_095,NEUTRAL,MINION,Weasel Tunneler,GANGS,<b>Deathrattle:</b> Shuffle this minion into y...,1.0,1.0,1.0,EPIC,1.0,He's the reason the First Bank of Gadgetzan ha...,BEAST,None,None,None,None,NaN,NaN,NaN
19,BRM_018,PALADIN,MINION,Dragon Consort,BRM,<b>Battlecry:</b> The next Dragon you play cos...,5.0,5.0,5.0,RARE,1.0,Everybody wants someone to snuggle with. Even ...,DRAGON,"Unlocked in Blackrock Spire, in the Blackrock ...","Crafting unlocked in Blackrock Spire, in the B...",None,None,NaN,NaN,NaN
20,PRO_001a,NEUTRAL,SPELL,I Am Murloc,PROMO,"Summon three, four, or five 1/1 Murlocs.",4.0,NaN,NaN,None,NaN,None,None,None,None,None,None,NaN,NaN,NaN
21,BRMA10_5H,NEUTRAL,MINION,Chromatic Drake,BRM,None,4.0,7.0,7.0,None,NaN,None,DRAGON,None,None,None,None,NaN,NaN,NaN
22,BRMA11_1,NEUTRAL,HERO,Vaelastrasz the Corrupt,BRM,None,NaN,NaN,30.0,None,NaN,None,None,None,None,None,None,NaN,NaN,NaN
23,OG_027,SHAMAN,SPELL,Evolve,OG,Transform your minions into random minions tha...,1.0,NaN,NaN,RARE,1.0,"So you say you want an evolution. Well, you kn...",None,None,None,None,None,NaN,NaN,NaN
24,NAX1_01,NEUTRAL,HERO,Anub'Rekhan,NAXX,None,NaN,NaN,30.0,None,NaN,None,None,None,None,None,None,NaN,NaN,NaN
25,GVG_030,DRUID,MINION,Anodized Robo Cub,GVG,<b>Taunt</b>. <b>Choose One -</b>\n+1 Attack; ...,2.0,2.0,2.0,COMMON,1.0,It's adorable! AND OH MY GOODNESS WHY IS IT EA...,MECHANICAL,None,None,None,None,NaN,NaN,NaN
26,CFM_094,WARLOCK,SPELL,Felfire Potion,GANGS,Deal $5 damage to all characters.,6.0,NaN,NaN,RARE,1.0,Kazakus has a squad of imps bottling Felfire r...,None,None,None,None,None,NaN,NaN,NaN
27,DS1h_292_H1,HUNTER,HERO_POWER,Steady Shot,HERO_SKINS,<b>Hero Power</b>\nDeal $2 damage to the enemy...,2.0,NaN,NaN,FREE,NaN,None,None,None,None,None,None,NaN,NaN,NaN
28,CS2_227,NEUTRAL,MINION,Venture Co. Mercenary,EXPERT1,Your minions cost (3) more.,5.0,7.0,6.0,COMMON,1.0,No Job is too big. No fee is too big.,None,None,None,None,HORDE,NaN,NaN,NaN
29,KAR_062,NEUTRAL,MINION,Netherspite Historian,KARA,"<b>Battlecry:</b> If you're holding a Dragon, ...",2.0,1.0,3.0,COMMON,1.0,She can tell you all about the history of peop...,None,"Unlocked in the Spire, in One Night in Karazhan.","Crafting unlocked in the Spire, in One Night i...",None,None,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
OG_338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DISENCHANT_NORMAL,400.0
OG_338,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DISENCHANT_GOLDEN,1600.0
OG_339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CRAFTING_NORMAL,100.0
OG_339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CRAFTING_GOLDEN,800.0
OG_339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DISENCHANT_NORMAL,20.0
OG_339,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DISENCHANT_GOLDEN,100.0
OG_340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CRAFTING_NORMAL,1600.0
OG_340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CRAFTING_GOLDEN,3200.0
OG_340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DISENCHANT_NORMAL,400.0
OG_340,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DISENCHANT_GOLDEN,1600.0
TB_OG_027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CRAFTING_NORMAL,100.0
TB_OG_027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CRAFTING_GOLDEN,800.0
TB_OG_027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DISENCHANT_NORMAL,20.0
TB_OG_027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DISENCHANT_GOLDEN,100.0
skele21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CRAFTING_NORMAL,40.0
skele21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CRAFTING_GOLDEN,400.0
skele21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DISENCHANT_NORMAL,5.0
skele21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DISENCHANT_GOLDEN,50.0
tt_004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CRAFTING_NORMAL,40.0
tt_004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CRAFTING_GOLDEN,400.0
tt_004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DISENCHANT_NORMAL,5.0
tt_004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DISENCHANT_GOLDEN,50.0
tt_010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CRAFTING_NORMAL,400.0
tt_010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CRAFTING_GOLDEN,1600.0
tt_010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DISENCHANT_NORMAL,100.0
tt_010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DISENCHANT_GOLDEN,400.0
tt_010a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CRAFTING_NORMAL,400.0
tt_010a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CRAFTING_GOLDEN,1600.0
tt_010a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DISENCHANT_NORMAL,100.0
tt_010a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DISENCHANT_GOLDEN,400.0

Inspect the output above.  Note that the naming collision has been avoided by renaming the `cost` column from the right table to `cost_dust`.  

## Summary

In this lab, we learned how to:

* Concatenate multiple DataFrames together into a single DataFrame
* Use `sqlalchemy` to connect to a sqlite database and read in individual tables as DataFrames
* Understand and execute the various types of joins (inner, outer, left, and right joins)